version: "3.8"

services:
  mysql:
    image: mariadb:10.6.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taosk
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
      TZ: "Asia/Tokyo"
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./docker/sql/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
